const STORAGE_KEY="cafe-bpx-state-v3";
const DEFAULT_COFFEES=[
{id:1,name:"Espresso",image:"images/espresso.svg",available:true},
{id:2,name:"Curto",image:"images/curto.svg",available:true},
{id:3,name:"Duplo",image:"images/coffee.svg",available:true},
{id:4,name:"Americano",image:"images/coffee.svg",available:true},
{id:5,name:"Cappuccino",image:"images/coffee.svg",available:true},
{id:6,name:"Café com leite",image:"images/coffee.svg",available:true},
{id:7,name:"Café com leite curto",image:"images/coffee.svg",available:true},
{id:8,name:"Nescau com leite",image:"images/nescau.svg",available:true},
{id:9,name:"Cappuccino Alpino",image:"images/alpino.svg",available:true},
{id:10,name:"Achocolatado Alpino",image:"images/alpino.svg",available:false},
{id:11,name:"Mokaccino Dois Frades",image:"images/frades.svg",available:false},
{id:12,name:"Achocolatado Dois Frades",image:"images/frades.svg",available:false}
];
function cloneState(data){return JSON.parse(JSON.stringify(data))}
function getCoffees(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return cloneState(DEFAULT_COFFEES);try{const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||parsed.length!==DEFAULT_COFFEES.length)return cloneState(DEFAULT_COFFEES);return parsed.map((item,index)=>({...DEFAULT_COFFEES[index],available:Boolean(item.available)}))}catch{return cloneState(DEFAULT_COFFEES)}}
function saveCoffees(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.setItem(STORAGE_KEY+":updatedAt",new Date().toISOString())}
function getAvailableText(data){const count=data.filter(item=>item.available).length;return `${count} de ${data.length} disponíveis`}
function formatUpdatedAt(){const stored=localStorage.getItem(STORAGE_KEY+":updatedAt");const date=stored?new Date(stored):new Date();const dd=String(date.getDate()).padStart(2,"0");const mm=String(date.getMonth()+1).padStart(2,"0");const hh=String(date.getHours()).padStart(2,"0");const min=String(date.getMinutes()).padStart(2,"0");return `Atualizado em ${dd}/${mm}, ${hh}:${min} · Consulta automática a cada 15 s`}
function createPublicCard(item){const article=document.createElement("article");article.className=`coffee-card ${item.available?"available":"unavailable"}`;const inner=document.createElement("div");inner.className="card-button";if(item.available){const icon=document.createElement("div");icon.className="card-top-icon";icon.textContent="✓";inner.append(icon)}const img=document.createElement("img");img.className="coffee-image";img.src=item.image;img.alt=item.name;img.loading="eager";img.decoding="async";const name=document.createElement("div");name.className="coffee-name";name.textContent=item.name;inner.append(img,name);article.append(inner);return article}
function renderHome(){const grid=document.getElementById("coffeeGrid");if(!grid)return;const data=getCoffees();grid.innerHTML="";data.forEach(item=>grid.appendChild(createPublicCard(item)));const availability=document.getElementById("publicAvailability");const lastUpdated=document.getElementById("lastUpdated");if(availability)availability.textContent=getAvailableText(data);if(lastUpdated)lastUpdated.textContent=formatUpdatedAt()}
function createAdminItem(item,data){const article=document.createElement("article");article.className="admin-item";const img=document.createElement("img");img.className="admin-thumb";img.src=item.image;img.alt=item.name;const info=document.createElement("div");info.className="admin-info";const name=document.createElement("p");name.className="admin-name";name.textContent=item.name;const meta=document.createElement("p");meta.className="admin-meta";meta.textContent=item.available?"Disponível":"Indisponível";info.append(name,meta);const label=document.createElement("label");label.className="switch";const input=document.createElement("input");input.type="checkbox";input.checked=item.available;input.setAttribute("aria-label",`Ativar ou desativar ${item.name}`);input.addEventListener("change",()=>{item.available=input.checked;meta.textContent=item.available?"Disponível":"Indisponível";const box=document.getElementById("adminAvailability");if(box)box.textContent=getAvailableText(data)});const ui=document.createElement("span");ui.className="switch-ui";label.append(input,ui);article.append(img,info,label);return article}
function showToast(message){let toast=document.querySelector(".toast");if(!toast){toast=document.createElement("div");toast.className="toast";document.body.appendChild(toast)}toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1800)}
function renderAdmin(){const grid=document.getElementById("adminGrid");if(!grid)return;const data=getCoffees();grid.innerHTML="";data.forEach(item=>grid.appendChild(createAdminItem(item,data)));const availability=document.getElementById("adminAvailability");if(availability)availability.textContent=getAvailableText(data);const saveBtn=document.getElementById("saveBtn");if(saveBtn)saveBtn.addEventListener("click",()=>{saveCoffees(data);if(availability)availability.textContent=getAvailableText(data);showToast("Status salvo com sucesso")})}
function initLogin(){const form=document.getElementById("loginForm");if(!form)return;form.addEventListener("submit",event=>{event.preventDefault();const user=document.getElementById("user").value.trim();const password=document.getElementById("password").value.trim();if(user==="admin"&&password==="admin"){window.location.href="admin.html";return}alert("Usuário ou senha inválidos.")})}
function init(){const page=document.body.dataset.page;if(!localStorage.getItem(STORAGE_KEY))saveCoffees(cloneState(DEFAULT_COFFEES));if(page==="home")renderHome();if(page==="admin")renderAdmin();if(page==="login")initLogin()}
document.addEventListener("DOMContentLoaded",init);